name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: themepark.catppuccin.com
          publish_dir: ./flavors
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
